### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Mar2ck** [tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary#1]
Program no longer works on the latest commit. Now it always ends with a segmentation fault
![Image](https://i.imgur.com/q7eCKQy.png)

**Comment by tanyiok1234** [comment]
> Program no longer works on the latest commit. Now it always ends with a segmentation fault
> ![Image](https://i.imgur.com/q7eCKQy.png)

I see ... It's the srmd-ncnn-vulkan, right?
I think it should works now ...

**Comment by Mar2ck** [comment]
I should've mentioned it before but its waifu2x that im having the issue with

**Comment by tanyiok1234** [comment]
> I should've mentioned it before but its waifu2x that im having the issue with

Well... waifu2x works on my cellphone, so I can't reproduce this bug. 
Could you try the patched srmd? If it works, I may have some ideas about how to fix it.

**Comment by Mar2ck** [comment]
Both srmd and waifu2x fail on the latest commit
![Screenshot_20200620-171440_Termux](https://user-images.githubusercontent.com/6759254/85206483-61d39800-b31a-11ea-844b-f36ed2b7f4bf.png)
![Screenshot_20200620-171524_Termux](https://user-images.githubusercontent.com/6759254/85206487-64ce8880-b31a-11ea-8e97-a010332486b9.png)

I downloaded the waifu2x binary from commit https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary/commit/d9bc82410c1bb06bd9892f6c593af02e7e96422a and that worked 
![Screenshot_20200620-171814_Termux](https://user-images.githubusercontent.com/6759254/85206499-79ab1c00-b31a-11ea-930a-d7d5ae401a1f.png)

**Comment by tanyiok1234** [comment]
> Both srmd and waifu2x fail on the latest commit
> ![Screenshot_20200620-171440_Termux](https://user-images.githubusercontent.com/6759254/85206483-61d39800-b31a-11ea-844b-f36ed2b7f4bf.png)
> ![Screenshot_20200620-171524_Termux](https://user-images.githubusercontent.com/6759254/85206487-64ce8880-b31a-11ea-8e97-a010332486b9.png)
> 
> I downloaded the waifu2x binary from commit https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary/commit/d9bc82410c1bb06bd9892f6c593af02e7e96422a and that worked 
> ![Screenshot_20200620-171814_Termux](https://user-images.githubusercontent.com/6759254/85206499-79ab1c00-b31a-11ea-930a-d7d5ae401a1f.png)
> 

The author of ncnn has updated lots of arm related codes since that commit.

Unfortunately I don't know to fix this problem, maybe next update on ncnn would fix it.

So please use binary from that commit for now, I will keep this issue open until it is fixed.

**Comment by Mar2ck** [comment]
Understandable, i can just use the old binary for now 👍

**Comment by tanyiok1234** [comment]
Hello, according to the advices from [@nihui](https://github.com/nihui/waifu2x-ncnn-vulkan/issues/87), I created a [new branch](https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary/tree/forolddevices) for old devices, could you try it?

**Comment by Mar2ck** [comment]
I tried that branch and it gives the same "Segmentation Fault" error. If it helps I'm using Android 9, Oneplus 6T, Vulkan Driver 512.324

**Comment by Mar2ck** [comment]
Do you remember what version of waifu2x-ncnn https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary/commit/d9bc82410c1bb06bd9892f6c593af02e7e96422a was a build of? The problem is probably something after that version

**Comment by tanyiok1234** [comment]
> 
> 
> Do you remember what version of waifu2x-ncnn [d9bc824](https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary/commit/d9bc82410c1bb06bd9892f6c593af02e7e96422a) was a build of? The problem is probably something after that version

Try [this](https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary/tree/forolddevices). 
![photo_2020-06-23_03-02-34](https://user-images.githubusercontent.com/11721926/85320471-111c9480-b4fe-11ea-8db9-8b0f6a40cf95.jpg)
If it doesn't work, then I am run out of ideas. but it should works.

**Comment by Mar2ck** [comment]
That one works perfectly!

**Comment by Mar2ck** [comment]
Master branch no longer segfaults on my phone
