### ISSUE TITLE
How did you build for ARMv8?

### ISSUE THREAD

**Issue by fluffyloopy** [tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary#3]
Could you please tell how you built this for termux? I've been unable to link vulkan to anything i've tried

**Comment by tanyiok1234** [comment]
You need to compile glslangValidator first, then combine it with the system built-in libvulkan.so to generate a "mini-vulkan SDK".

Then export it to the VULKAN_SDK environment variable.
 
if you need libvulkan.so, go to /system/lib64/libvulkan.so

**Comment by fluffyloopy** [comment]
How do I do that? I have compiled it but have no idea on how to combine it with /system/lib64/libvulkan.so
I know how to export path but no idea about vulkan SDK related stuff.

**Comment by tanyiok1234** [comment]
> How do I do that? I have compiled it but have no idea on how to combine it with /system/lib64/libvulkan.so
> I know how to export path but no idea about vulkan SDK related stuff. Reading about the API or glslang git didn't help me much as I don't fully understand these. 

Put libvulkan.so into [your build dir]/install/lib

export VULKAN_SDK=[your build dir]/install

![Screenshot_20201212-040551609_1.jpg](https://user-images.githubusercontent.com/11721926/101944114-8d7f6d00-3c2f-11eb-8241-261abb1e6ac1.jpg)

**Comment by fluffyloopy** [comment]
![image](https://user-images.githubusercontent.com/36381994/101950227-ba735600-3c16-11eb-83bf-0fef43d01d01.png)
Did this happen while you were building too? If so, why does this happen?

**Comment by tanyiok1234** [comment]
> ![image](https://user-images.githubusercontent.com/36381994/101950227-ba735600-3c16-11eb-83bf-0fef43d01d01.png)
> Did this happen while you were building too? If so, why does this happen?

Please clone the repository forked by me, otherwise you will need to solve many compile issues.
